<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PRo3D.Viewer.SimpleGui</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Include="paket.references" />
    <None Include="RunAdaptify.fsx" />
    <Compile Include="Model.fs" />
    <Compile Include="Model.g.fs" />
    <Compile Include="OpcLoading.fs" />
    <Compile Include="App.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
